# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  username: depot
  password: <%= ENV['DEPOT_DATABASE_PASSWORD'] %>

